# Generated by Django 4.2.5 on 2023-09-28 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_rating'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Author',
            new_name='Auther',
        ),
        migrations.AddField(
            model_name='book',
            name='available',
            field=models.IntegerField(default=100),
        ),
    ]
