# Generated by Django 4.2.5 on 2023-09-28 13:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_rename_author_auther_book_available'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='borrowed',
        ),
    ]
