# Generated by Django 4.2.5 on 2023-10-07 14:14

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_remove_book_borrowed'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='page',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='book',
            name='auther',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='auther_books', to='api.auther'),
        ),
        migrations.AlterField(
            model_name='book',
            name='available',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
