# Generated by Django 4.2.5 on 2023-11-18 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_rename_page_book_pages_book_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='borrow',
            name='time',
            field=models.DateField(auto_now=True),
        ),
    ]
